services:
  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sentinel

  backend:
    build:
      context: ./sentinel-backend/sentinel-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on: 
      - db

  frontend:
    build:
      context: ./sentinel-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes: 
  postgres_data: