version: '3.8'
services:
  backend:
    build: 
      context: ./sentinel-backend/sentinel-backend
    ports: 
      - "8080:8080" 

  frontend: 
    build:
      context: ./sentinel-frontend 
    ports: 
      - "4200:80"
    depends_on: 
      - backend